title: Asesorías Educativas
email: hola@asesoreducativo.mx
author: Carlos Chee
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# DO NOT CHANGE THE LINE OF THIS FILE without editing .circleci/circle_urls.sh
baseurl: "/" # the subpath of your site, e.g. /blog

# This is mostly for testing
url: "https://aula.asesoreducativo.mx/" # the base hostname & protocol for your site

# Social (First three Required)
repo: "https://github.com/vsoch/mkdocs-jekyll"
github_user: "vsoch"
github_repo: "mkdocs-jekyll"

# Optional
twitter: asesoredumx
linkedin: carlos-manuel-chee-vázquez-130bba183
dockerhub: vanessa
# google-analytics: UA-XXXXXXXXXX
# Image and (square) dimension for logo (don't start with /)
# If commented, will use material hat theme
# logo: "assets/img/logo/SRCC-square-red.png"
logo_width: 34
color: "#004488" # primary color for header, buttons

# Build settings
markdown: kramdown

# If you add tags to pages, you can link them to some external search
# If you want to disable this, comment the URL.
tag_search_endpoint: https://ask.cyberinfrastructure.org/search?q=
tag_color: info # danger, success, warning, primary, info, secondary

# Add a page at /forum to list a set of discourse topics. The site needs
# to enable "embed topics" setting
# https://meta.discourse.org/t/embedding-a-list-of-discourse-topics-in-another-site/125911
discourse_site: "https://ask.cyberinfrastructure.org" 
discourse_per_page: 10
discourse_category: "stanford-research-computing"
discourse_tags: null # comma separated string, leave null to not filter

accentColor: green # purple, green, etc.
themeColor: red # purple, green, blue, orange, purple, grey
fixedNav: 'true' # true or false

permalink: /:year/:title/
markdown: kramdown
exclude: [_site, CHANGELOG.md, LICENSE, README.md, vendor]

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:path

# Defaults
defaults:
  - scope:
      path: "_docs"
      type: "docs"
    values:
      layout: page
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: "posts"
      type: "posts"
    values:
      layout: "post"
